/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenuItem;

/**
 *
 * @author Isaac
 */
public class PrincipalView extends javax.swing.JFrame {
    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    public JMenuItem getItemAgencia() {
        return itemAgencia;
    }

    public JMenuItem getItemDiretoria() {
        return itemDiretoria;
    }

    public JMenuItem getItemGerente() {
        return itemGerente;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        itemDiretoria = new javax.swing.JMenuItem();
        itemGerente = new javax.swing.JMenuItem();
        itemAgencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        menuOpcoes.setText("Opções");

        itemDiretoria.setText("Diretoria");
        menuOpcoes.add(itemDiretoria);

        itemGerente.setText("Gerentes");
        itemGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGerenteActionPerformed(evt);
            }
        });
        menuOpcoes.add(itemGerente);

        itemAgencia.setText("Agências");
        itemAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgenciaActionPerformed(evt);
            }
        });
        menuOpcoes.add(itemAgencia);

        jMenuBar1.add(menuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGerenteActionPerformed

    private void itemAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgenciaActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgencia;
    private javax.swing.JMenuItem itemDiretoria;
    private javax.swing.JMenuItem itemGerente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
